### ISSUE TITLE
anaconda prompt安装错误怎么办？

### ISSUE THREAD

**Issue by shanleyao** [geatpy-dev/geatpy#105]
(base) C:\Users\****>pip install geatpy
Collecting geatpy
  Downloading geatpy-2.4.0-cp37-cp37m-win_amd64.whl (2.8 MB)
     |                                | 20 kB 5.4 kB/s eta 0:08:26ERROR: Exception:
Traceback (most recent call last):
  File "d:\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 425, in _error_catcher
    yield
  File "d:\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "d:\anaconda3\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "d:\anaconda3\lib\http\client.py", line 457, in read
    n = self.readinto(b)
  File "d:\anaconda3\lib\http\client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "d:\anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "d:\anaconda3\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "d:\anaconda3\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
    status = self.run(options, args)
  File "d:\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "d:\anaconda3\lib\site-packages\pip\_internal\legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "d:\anaconda3\lib\site-packages\pip\_internal\legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "d:\anaconda3\lib\site-packages\pip\_internal\legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "d:\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 482, in prepare_linked_requirement
    hashes=hashes,
  File "d:\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 287, in unpack_url
    hashes=hashes,
  File "d:\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 159, in unpack_http_url
    link, downloader, temp_dir.path, hashes
  File "d:\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 303, in _download_http_url
    for chunk in download.chunks:
  File "d:\anaconda3\lib\site-packages\pip\_internal\utils\ui.py", line 160, in iter
    for x in it:
  File "d:\anaconda3\lib\site-packages\pip\_internal\network\utils.py", line 39, in response_chunks
    decode_content=False,
  File "d:\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "d:\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "d:\anaconda3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "d:\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by geatpy-dev** [comment]
@shanleyao 由上述错误信息可见是连接超时了，切换豆瓣源安装（控制台执行下方命令）：
pip install -i http://pypi.douban.com/simple/ --trusted-host=pypi.douban.com/simple geatpy==2.5.0rc0
