### ISSUE TITLE
UnicodeDecodeError in installing

### ISSUE THREAD

**Issue by ShuteLee** [geatpy-dev/geatpy#13]
When my installing:

Exception:
Traceback (most recent call last):
  File "/home/server5/anaconda3/envs/tf19/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/home/server5/anaconda3/envs/tf19/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/home/server5/anaconda3/envs/tf19/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/home/server5/anaconda3/envs/tf19/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 913, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/home/server5/anaconda3/envs/tf19/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 445, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/home/server5/anaconda3/envs/tf19/lib/python3.6/site-packages/pip/_internal/wheel.py", line 607, in move_wheel_files
    generated=generated, lib_dir=lib_dir,
  File "/home/server5/anaconda3/envs/tf19/lib/python3.6/site-packages/pip/_internal/wheel.py", line 275, in get_csv_rows_for_installed
    for row in old_csv_rows:
  File "/home/server5/anaconda3/envs/tf19/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 4333: invalid continuation byte

I do not know what caused this and how to figure it out

**Comment by 1061655504** [comment]
> When my installing:
> 
> Exception:
> Traceback (most recent call last):
> File "/home/server5/anaconda3/envs/tf19/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 179, in main
> status = self.run(options, args)
> File "/home/server5/anaconda3/envs/tf19/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 393, in run
> use_user_site=options.use_user_site,
> File "/home/server5/anaconda3/envs/tf19/lib/python3.6/site-packages/pip/_internal/req/**init**.py", line 57, in install_given_reqs
> **kwargs
> File "/home/server5/anaconda3/envs/tf19/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 913, in install
> use_user_site=use_user_site, pycompile=pycompile,
> File "/home/server5/anaconda3/envs/tf19/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 445, in move_wheel_files
> warn_script_location=warn_script_location,
> File "/home/server5/anaconda3/envs/tf19/lib/python3.6/site-packages/pip/_internal/wheel.py", line 607, in move_wheel_files
> generated=generated, lib_dir=lib_dir,
> File "/home/server5/anaconda3/envs/tf19/lib/python3.6/site-packages/pip/_internal/wheel.py", line 275, in get_csv_rows_for_installed
> for row in old_csv_rows:
> File "/home/server5/anaconda3/envs/tf19/lib/python3.6/codecs.py", line 321, in decode
> (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 4333: invalid continuation byte
> 
> I do not know what caused this and how to figure it out

这个问题跟pip的设置、安装方式等一些方面有关，可以尝试用管理员方式安装，如：
pip install --user geatpy
或pip install --user --upgrade geatpy
