### ISSUE TITLE
多目标案例运行报错

### ISSUE THREAD

**Issue by codersdady** [geatpy-dev/geatpy#162]
```
Traceback (most recent call last):
  File "E:/workspace/多目标/main.py", line 25, in <module>
    [NDSet, population] = myAlgorithm.run()  # 执行算法模板，得到非支配种群以及最后一代种群
  File "C:\Anaconda3\lib\site-packages\geatpy\Population.py", line 152, in __getitem__
    raise RuntimeError('error in Population: index must be a 1-D array. (index必须是一个一维的向量。)')
RuntimeError: error in Population: index must be a 1-D array. (index必须是一个一维的向量。)
```
您好，多目标的案例，报这个错是什么原因

**Comment by geatpy-dev** [comment]
@codersdady 问题同见[https://github.com/geatpy-dev/geatpy/issues/157](url) 在Population.py里报错的那一行上面print()一下是什么类型导致报错，然后添加新类型进后面那段类型检查语句中。

**Comment by codersdady** [comment]
> @codersdady 问题同见[https://github.com/geatpy-dev/geatpy/issues/157](url) 在Population.py里报错的那一行上面print()一下是什么类型导致报错，然后添加新类型进后面那段类型检查语句中。

您好，我已经在Population中强制转类型，解决了这个报错，但又有一个新的错误，我把整个项目clone下来运行仍旧是这个错误。
```
Traceback (most recent call last):
  File "E:/workspace/多目标/geatpy/geatpy/demo/moea_demo/moea_demo1/main.py", line 27, in <module>
    [NDSet, population] = myAlgorithm.run()  # 执行算法模板，得到非支配种群以及最后一代种群
ValueError: not enough values to unpack (expected 2, got 0)
```
这是需要改什么内容吗，为什么看别人都能直接运行？

**Comment by geatpy-dev** [comment]
@codersdady 你的python里面的geatpy版本错乱了。彻底删除后用pip重装一下。

**Comment by codersdady** [comment]
> @codersdady 你的python里面的geatpy版本错乱了。彻底删除后用pip重装一下。

感谢，问题解决，是版本的问题。
