### ISSUE TITLE
 from awGA import awGA ModuleNotFoundError: No module named 'awGA'

### ISSUE THREAD

**Issue by wenqing0220** [geatpy-dev/geatpy#163]
Connected to pydev debugger (build 201.8743.11)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\02_SVNCode\geatpy-master\geatpy\__init__.py", line 16, in <module>
    from awGA import awGA
ModuleNotFoundError: No module named 'awGA'

python 3.8.6
geatpy  版本 2.6.0

**Comment by wenqing0220** [comment]
pip  version is 20.3.1

**Comment by geatpy-dev** [comment]
这个意思就是安装失败了，彻底卸载用命令行pip install geatpy安装试一下。

**Comment by thatda1** [comment]
你好，我安装一直提示“for files in os.listdir(path):
    FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '_core/Windows/lib64/v3.9'”
安装不成功，只能安装2.0.0版本，
运行的时候就会报错“from awGA import awGA
ImportError: cannot import name 'awGA' from 'awGA' (unknown location)”

请问怎么解决

**Comment by Mr-Doufasheng** [comment]
@geatpy-dev geatpy/__init__.py中好多引用都找不到declaration，项目git下来后直接跑里面的demo就会从__init__.py里的第一个引用开始报错，就是这里提到的No module named 'awGA' ，请问这里from xxx import xxx导入的module是在哪里实现的？找不到declaration是否只是pycharm工具的问题？可以确定不是安装问题，因为单独新建一个项目，把demo code copy进去，是可以正常运行的，而且git下来的项目虚拟环境中pip uninstall后再install还是一样会报No module named 'awGA' 。
cannot find declaration截图如下：
<img width="709" alt="no declaration" src="https://user-images.githubusercontent.com/34061363/130386460-e79251ea-76e6-470a-97d0-95b2b93c7868.png">
<img width="792" alt="no_declaration_2" src="https://user-images.githubusercontent.com/34061363/130386462-56436109-ad24-496d-88ad-7387f7c77864.png">

**Comment by zhuohoudeputao** [comment]
我是直接在终端当中运行
```
python3
>>> import geatpy
```
都会出现这个报错

**Comment by WarriorOfShadow** [comment]
> @geatpy-dev geatpy/**init**.py中好多引用都找不到declaration，项目git下来后直接跑里面的demo就会从__init__.py里的第一个引用开始报错，就是这里提到的No module named 'awGA' ，请问这里from xxx import xxx导入的module是在哪里实现的？找不到declaration是否只是pycharm工具的问题？可以确定不是安装问题，因为单独新建一个项目，把demo code copy进去，是可以正常运行的，而且git下来的项目虚拟环境中pip uninstall后再install还是一样会报No module named 'awGA' 。 cannot find declaration截图如下： <img alt="no declaration" width="709" src="https://user-images.githubusercontent.com/34061363/130386460-e79251ea-76e6-470a-97d0-95b2b93c7868.png"> <img alt="no_declaration_2" width="792" src="https://user-images.githubusercontent.com/34061363/130386462-56436109-ad24-496d-88ad-7387f7c77864.png">

这种情况可能是因为你在项目目录里面运行导致包冲突了，你只需要将demo放置在一个项目外面的地方运行就行了，像这样：
![image](https://user-images.githubusercontent.com/74849229/154411969-873b0c2e-4f9d-4b87-98c3-48161ebceeec.png)
