### ISSUE TITLE
希望能够加入对AppleM1的支持

### ISSUE THREAD

**Issue by DawnMagnet** [geatpy-dev/geatpy#176]
希望能够加入对macos-aarch64的支持
我的MacAir M1在安装geatpy(从源码构建)时报错
```bash
❯ pip install geatpy
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting geatpy
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6a/be/195167884ff2fb6859cac2f32c8d351db7460df72e15f7afc1a7616b11d3/geatpy-2.4.0.tar.gz (60.0 MB)
     |████████████████████████████████| 60.0 MB 1.6 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/dawnmagnet/mambaforge/envs/sci/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/95/366sqff14fg880xf2pdzy2qr0000gn/T/pip-install-_b8cfc3j/geatpy_6363010b944349d69465077f7938fe42/setup.py'"'"'; __file__='"'"'/private/var/folders/95/366sqff14fg880xf2pdzy2qr0000gn/T/pip-install-_b8cfc3j/geatpy_6363010b944349d69465077f7938fe42/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/95/366sqff14fg880xf2pdzy2qr0000gn/T/pip-pip-egg-info-xy14932d
         cwd: /private/var/folders/95/366sqff14fg880xf2pdzy2qr0000gn/T/pip-install-_b8cfc3j/geatpy_6363010b944349d69465077f7938fe42/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/95/366sqff14fg880xf2pdzy2qr0000gn/T/pip-install-_b8cfc3j/geatpy_6363010b944349d69465077f7938fe42/setup.py", line 75, in <module>
        findAndCopy(core_path)
      File "/private/var/folders/95/366sqff14fg880xf2pdzy2qr0000gn/T/pip-install-_b8cfc3j/geatpy_6363010b944349d69465077f7938fe42/setup.py", line 58, in findAndCopy
        for files in os.listdir(path):
    FileNotFoundError: [Errno 2] No such file or directory: '_core/Darwin/lib64/v3.9'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by geatpy-dev** [comment]
好滴~

**Comment by xlgosin** [comment]
请问这个问题，目前如何解决？
