### ISSUE TITLE
ImportError: cannot import name comb

### ISSUE THREAD

**Issue by PeterFanFan** [geatpy-dev/geatpy#180]
Traceback (most recent call last):
  File "D:/objectselect/demo/soea_demo/soea_demo1/main.py", line 2, in <module>
    import geatpy as ea  # import geatpy
  File "D:\Anaconda\envs\py3\lib\site-packages\geatpy-2.6.0-py3.6.egg\geatpy\__init__.py", line 31, in <module>
    from crtup import crtup
  File "core\crtup.py", line 3, in init crtup
ImportError: cannot import name comb

**Comment by geatpy-dev** [comment]
It's a problem of your scipy.

Reinstall the package "scipy" until you can run the following command successfully:

`from scipy.special import comb`
