### ISSUE TITLE
基于Geatpy的项目打包时出现问题

### ISSUE THREAD

**Issue by PeterFanFan** [geatpy-dev/geatpy#184]
在用pyinstaller将项目打包为exe文件，在运行文件时提示以下错误
D:\GAprobject1.0\dist\GA_main_Parallel>GA_main_Parallel.exe
Traceback (most recent call last):
  File "GA_main_Parallel.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "geatpy\__init__.py", line 16, in <module>
ModuleNotFoundError: No module named 'awGA'
[26172] Failed to execute script GA_main_Parallel

**Comment by geatpy-dev** [comment]
该问题同[https://github.com/geatpy-dev/geatpy/issues/129](url) 不是这个工具箱的问题。
