### ISSUE TITLE
并行多目标优化时，numpy数组相关代码报错

### ISSUE THREAD

**Issue by SYH0323** [geatpy-dev/geatpy#304]
我是做整数规划的，目标函数如下，优化目标有两个，约束有一个。
`def subAimFunc(x):
    PV, ESS, CFPP = initialize(x)
    PV, ESS, CFPP, power_shortage = operation(Solar, Load, PV, ESS, CFPP)

    LPSP = sum(power_shortage) / sum(Load)
    carbon_per_power = 1000 * sum(CFPP.carbon) / (sum(Load) - sum(power_shortage) + ESS.E[-1] - ESS.E[0])
    LCOE = price_per_power(Load, PV, ESS, CFPP, power_shortage)

    ObjV = np.hstack([LPSP, carbon_per_power, LCOE])
    return ObjV`

决策变量是一个四维数组，每执行一次目标函数需要0.25秒左右，虽然执行比较快，但是因为搜索空间很大（1000*1000*10000*120），所以打算采用并行模式提高效率。
但是报了下面的错，查了一些资料，说是数组错位了，但我是真的看不懂，求大家懂行的回答一下吧。
`Traceback (most recent call last):
  File "D:/SYH/PV_CFPP/多目标优化测试/MyProblem-并行.py", line 106, in <module>
    res = ea.optimize(algorithm, verbose=True, drawing=1, outputMsg=True, drawLog=False, saveFlag=True)
  File "D:\anoconda\lib\site-packages\geatpy\optimize.py", line 104, in optimize
    [optPop, lastPop] = algorithm.run(prophetPop)
  File "D:\anoconda\lib\site-packages\geatpy\algorithms\moeas\nsga2\moea_NSGA2_templet.py", line 87, in run
    [levels, _] = self.ndSort(population.ObjV, NIND, None, population.CV, self.problem.maxormins)  # 对NIND个个体进行非支配分层
  File "core\c\ndsortESS.pyx", line 170, in ndsortESS.ndsortESS
ValueError: setting an array element with a sequence.`

**Comment by Hayden-CHENPRO** [comment]
并行的时候有过爆内存的经历嘛

**Comment by SYH0323** [comment]
> 并行的时候有过爆内存的经历嘛

我用的pycharm，最多2000个种群，迭代1000次，没有爆内存。
