### ISSUE TITLE
 installation error

### ISSUE THREAD

**Issue by 751613605** [geatpy-dev/geatpy#341]
在安装geatpy时发生错误
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting geatpy
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/6a/be/195167884ff2fb6859cac2f32c8d351db7460df72e15f7afc1a7616b11d3/geatpy-2.4.0.tar.gz (60.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\86185\AppData\Local\Temp\pip-install-w3xpqk57\geatpy_bc711c5e37a04713bafd5a4db3eb1c4d\setup.py", line 75, in <module>
          findAndCopy(core_path)
        File "C:\Users\86185\AppData\Local\Temp\pip-install-w3xpqk57\geatpy_bc711c5e37a04713bafd5a4db3eb1c4d\setup.py", line 58, in findAndCopy
          for files in os.listdir(path):
                       ^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '_core/Windows/lib64/v3.1'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

网上找了好多资料无果还请指点
谢谢

**Comment by geatpy-dev** [comment]
改用pip安装
