### ISSUE TITLE
搞了两天了，安装不了

### ISSUE THREAD

**Issue by lanyilin666** [geatpy-dev/geatpy#379]
C:\Users\30110>pip install geatpy
Collecting geatpy
  Using cached geatpy-2.4.0.tar.gz (60.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\30110\AppData\Local\Temp\pip-install-j1f8w25r\geatpy_cd0e2c4429d6468da02329939f143e4c\setup.py", line 75, in <module>
          findAndCopy(core_path)
        File "C:\Users\30110\AppData\Local\Temp\pip-install-j1f8w25r\geatpy_cd0e2c4429d6468da02329939f143e4c\setup.py", line 58, in findAndCopy
          for files in os.listdir(path):
                       ^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '_core/Windows/lib64/v3.1'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Decade-rider** [comment]
可以本地安装试试呢，我刚刚安装2.7.0成功了
我的命令如下：pip install XXX\geatpy-2.7.0-cp311-cp311-win_amd64.whl
先下载适合自己python版本的whl文件，再进行本地安装。XXX是你的whl文件所在路径

**Comment by lanyilin666** [comment]
我python版本是3.12
好像不支持这个版本吧

**Comment by Decade-rider** [comment]
2.7是有支持3.12的可以下载的

**Comment by geatpy-dev** [comment]
在Github release里可以下载Python 3.12的版本的安装包。

**Comment by lanyilin666** [comment]
哦哦，我把我python版本转成3.10了，一下就安好了，谢谢各位

**Comment by HuangZR-stu** [comment]
> 可以本地安装试试呢，我刚刚安装2.7.0成功了 我的命令如下：pip install XXX\geatpy-2.7.0-cp311-cp311-win_amd64.whl 先下载适合自己python版本的whl文件，再进行本地安装。XXX是你的whl文件所在路径

我为什么克隆下载了之后，没有看到whl 文件呢，请问是怎么本地安装的呢？
