### ISSUE TITLE
Issues related to installing the geatpy library

### ISSUE THREAD

**Issue by Lee12345682** [geatpy-dev/geatpy#381]
**Describe the bug**

> Although the numpy library is installed, it still shows that it is not installed. The relevant error message is as follows：

Collecting geatpy==2.3.0
  Using cached geatpy-2.3.0.tar.gz (58.6 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [8 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\l3188975043\AppData\Local\Temp\pip-install-0kholrul\geatpy_7a8a3643745e4344be8265a3e374f321\setup.py", line 75, in <module>
      findAndCopy(core_path)
    File "C:\Users\l3188975043\AppData\Local\Temp\pip-install-0kholrul\geatpy_7a8a3643745e4344be8265a3e374f321\setup.py", line 58, in findAndCopy
      for files in os.listdir(path):
  FileNotFoundError: [WinError 3] ϵͳ�Ҳ���ָ����·����: '_core/Windows/lib64/v3.9'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by twb1235** [comment]
使用清华镜像源时候，安装的是2.4.0版本出现以上问题
直接下载release中2.7.0版本的whl，pip安装成功
