### ISSUE TITLE
安装不了

### ISSUE THREAD

**Issue by chenchenT** [geatpy-dev/geatpy#387]
pip install geatpy 报错了

Collecting geatpy
  Using cached geatpy-2.4.0.tar.gz (60.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/9b/bsy0zccs53342bvycfcbd0600000gn/T/pip-install-lg71u89o/geatpy_64b721e62fb44f7f8e0833d6e81afd51/setup.py", line 75, in <module>
          findAndCopy(core_path)
        File "/private/var/folders/9b/bsy0zccs53342bvycfcbd0600000gn/T/pip-install-lg71u89o/geatpy_64b721e62fb44f7f8e0833d6e81afd51/setup.py", line 58, in findAndCopy
          for files in os.listdir(path):
                       ^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '_core/Darwin/lib64/v3.1'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

python 版本是3.12，我看了release里面的，好像没有提供macos系统的cp312的.whl

**Comment by chenchenT** [comment]
python降级为3.10后安装成功了，但是不兼容架构
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[/var/folders/9b/bsy0zccs53342bvycfcbd0600000gn/T/ipykernel_18834/3925503107.py](http://localhost:8890/var/folders/9b/bsy0zccs53342bvycfcbd0600000gn/T/ipykernel_18834/3925503107.py) in <module>
----> 1 import geatpy as ea

[/opt/anaconda3/lib/python3.10/site-packages/geatpy/__init__.py](http://localhost:8890/opt/anaconda3/lib/python3.10/site-packages/geatpy/__init__.py) in <module>
      9 
     10 # import the core
---> 11 from geatpy.core.awGA import awGA
     12 from geatpy.core.boundfix import boundfix
     13 from geatpy.core.bs2int import bs2int

ImportError: dlopen([/opt/anaconda3/lib/python3.10/site-packages/geatpy/core/awGA.cpython-310-darwin.so](http://localhost:8890/opt/anaconda3/lib/python3.10/site-packages/geatpy/core/awGA.cpython-310-darwin.so), 0x0002): tried: '[/opt/anaconda3/lib/python3.10/site-packages/geatpy/core/awGA.cpython-310-darwin.so](http://localhost:8890/opt/anaconda3/lib/python3.10/site-packages/geatpy/core/awGA.cpython-310-darwin.so)' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
