### ISSUE TITLE
ValueError: left cannot be >= right in trcplot.trcplot?

### ISSUE THREAD

**Issue by daisyzhangty** [geatpy-dev/geatpy#6]
hello, I got an error when  running all the demos, The error was showed that  ValueError: left cannot be >= right，the details were as followed.
Traceback (most recent call last):
  File "E:/Test/GA/demo/quickstart_demo/quickstart_demo.py", line 74, in <module>
    ga.trcplot(pop_trace, [['种群个体平均目标函数值', '种群最优个体目标函数值']], ['demo_result'])
  File "geatpy\trcplot.py", line 76, in trcplot.trcplot
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\matplotlib\pyplot.py", line 253, in show
    return _show(*args, **kw)
  File "D:\PyCharm 2018.2.1\helpers\pycharm_matplotlib_backend\backend_interagg.py", line 25, in __call__
    manager.show(**kwargs)
  File "D:\PyCharm 2018.2.1\helpers\pycharm_matplotlib_backend\backend_interagg.py", line 107, in show
    self.canvas.show()
  File "D:\PyCharm 2018.2.1\helpers\pycharm_matplotlib_backend\backend_interagg.py", line 62, in show
    self.figure.tight_layout()
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\matplotlib\figure.py", line 2276, in tight_layout
    self.subplots_adjust(**kwargs)
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\matplotlib\figure.py", line 2088, in subplots_adjust
    self.subplotpars.update(*args, **kwargs)
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\matplotlib\figure.py", line 241, in update
    raise ValueError('left cannot be >= right')
ValueError: left cannot be >= right
And i do not know how to deal with it.

**Comment by daisyzhangty** [comment]
Thank you，teacher. Thank you very much for your answer. The operation is successful.
