### ISSUE TITLE
排列编码决策变量较多时报错‘染色体不满足排列编码规则’

### ISSUE THREAD

**Issue by ImLaoBJie** [geatpy-dev/geatpy#91]
### Scenario：
1. 混合编码
2. 使用过的模板soea_psy_XXX_templet.py
3. version: geatpy-2.4.1
---
### 错误复现
以`geatpy/geatpy/demo/soea_demo/soea_demo5/MyProblem.py/ `这个demo为例，当混合编码决策变量个数为4个，取值范围为[1, 7]，也就是demo里的场景，正常，

但是如果我将上下界扩大到一个较大的范围，比如[0, 63]，将会有以下两种情况：

### 1. 未出现错误的情况
当决策变量个数（也就是64）刚好等于上下界的范围时：（这里修改自soea_demo5，通过增加几个无用决策变量复现问题）
```
import numpy as np
import geatpy as ea


class MyProblem(ea.Problem):  # 继承Problem父类
    def __init__(self):
        name = 'MyProblem'  # 初始化name（函数名称，可以随意设置）
        M = 1  # 初始化M（目标维数）
        maxormins = [-1]  # 初始化maxormins（目标最小最大化标记列表，1：最小化该目标；-1：最大化该目标
        # ##############################################################################################################
        # 此处做了修改
        Dim = 2 + (4 + 60)  # 初始化Dim（决策变量维数）
        varTypes = [0, 0, 1, 1, 1, 1] + [1] * 60 # 初始化varTypes（决策变量的类型，元素为0表示对应的变量是连续的；1表示是离散的）
        lb = [-1.5, -1.5, 0, 0, 0, 0] + [0] * 60  # 决策变量下界
        ub = [2.5, 2.5, 63, 63, 63, 63] + [63] * 60  # 决策变量上界
        # 此处做了修改
        # ##############################################################################################################
        lbin = [1] * Dim  # 决策变量下边界（0表示不包含该变量的下边界，1表示包含）
        ubin = [1] * Dim  # 决策变量上边界（0表示不包含该变量的上边界，1表示包含）
        # 调用父类构造方法完成实例化
        ea.Problem.__init__(self, name, M, maxormins, Dim, varTypes, lb, ub, lbin, ubin)

    def aimFunc(self, pop):  # 目标函数
        X = pop.Phen  # 得到决策变量矩阵
        x1 = X[:, [0]]
        x2 = X[:, [1]]
        x3 = X[:, [2]]
        x4 = X[:, [3]]
        x5 = X[:, [4]]
        x6 = X[:, [5]]
        pop.ObjV = np.sin(2 * x1) - np.cos(x2) + 2 * x3 ** 2 - 3 * x4 + (
                    x5 - 3) ** 2 + 7 * x6  # 计算目标函数值，赋值给pop种群对象的ObjV属性

if __name__ == '__main__':
    """================================实例化问题对象==========================="""
    problem = MyProblem() # 生成问题对象
    """==================================种群设置==============================="""
    NIND = 40             # 种群规模
    # 创建区域描述器，这里需要创建两个，前2个变量用RI编码，剩余变量用排列编码
    Encodings = ['RI', 'P']
    Field1 = ea.crtfld(Encodings[0], problem.varTypes[:2], problem.ranges[:,:2], problem.borders[:,:2])
    Field2 = ea.crtfld(Encodings[1], problem.varTypes[2:], problem.ranges[:,2:], problem.borders[:,2:])
    Fields = [Field1, Field2]
    population = ea.PsyPopulation(Encodings, Fields, NIND) # 实例化种群对象（此时种群还没被初始化，仅仅是完成种群对象的实例化）
    """================================算法参数设置============================="""
    myAlgorithm = ea.soea_psy_EGA_templet(problem, population) # 实例化一个算法模板对象
    myAlgorithm.MAXGEN = 25 # 最大进化代数
    """===========================调用算法模板进行种群进化======================="""
    [population, obj_trace, var_trace] = myAlgorithm.run() # 执行算法模板
    population.save() # 把最后一代种群的信息保存到文件中
    # 输出结果
    best_gen = np.argmin(problem.maxormins * obj_trace[:, 1]) # 记录最优种群个体是在哪一代
    best_ObjV = obj_trace[best_gen, 1]
    print('最优的目标函数值为：%s'%(best_ObjV))
    print('最优的控制变量值为：')
    for i in range(var_trace.shape[1]):
        print(var_trace[best_gen, i])
    print('有效进化代数：%s'%(obj_trace.shape[0]))
    print('最优的一代是第 %s 代'%(best_gen + 1))
    print('评价次数：%s'%(myAlgorithm.evalsNum))
    print('时间已过 %s 秒'%(myAlgorithm.passTime))
```
运行正常：
贴个结果
![image](https://user-images.githubusercontent.com/48209234/76239320-53caa180-626c-11ea-8cc9-154b53c7a038.png)

### 2. 出现错误的情况
但是当决策变量个数（也就是`<(ub - lb + 1)`，这里取44，或者随意一个小于64的数）少于上下界的范围时：（这里修改自soea_demo5，通过增加几个无用决策变量复现问题）
```
import numpy as np
import geatpy as ea


class MyProblem(ea.Problem):  # 继承Problem父类
    def __init__(self):
        name = 'MyProblem'  # 初始化name（函数名称，可以随意设置）
        M = 1  # 初始化M（目标维数）
        maxormins = [-1]  # 初始化maxormins（目标最小最大化标记列表，1：最小化该目标；-1：最大化该目标
        # ##############################################################################################################
        # 此处做了修改
        Dim = 2 + (4 + 40)  # 初始化Dim（决策变量维数）
        varTypes = [0, 0, 1, 1, 1, 1] + [1] * 40 # 初始化varTypes（决策变量的类型，元素为0表示对应的变量是连续的；1表示是离散的）
        lb = [-1.5, -1.5, 0, 0, 0, 0] + [0] * 40  # 决策变量下界
        ub = [2.5, 2.5, 63, 63, 63, 63] + [63] * 40  # 决策变量上界
        # 此处做了修改
        # ##############################################################################################################
        lbin = [1] * Dim  # 决策变量下边界（0表示不包含该变量的下边界，1表示包含）
        ubin = [1] * Dim  # 决策变量上边界（0表示不包含该变量的上边界，1表示包含）
        # 调用父类构造方法完成实例化
        ea.Problem.__init__(self, name, M, maxormins, Dim, varTypes, lb, ub, lbin, ubin)

    def aimFunc(self, pop):  # 目标函数
        X = pop.Phen  # 得到决策变量矩阵
        x1 = X[:, [0]]
        x2 = X[:, [1]]
        x3 = X[:, [2]]
        x4 = X[:, [3]]
        x5 = X[:, [4]]
        x6 = X[:, [5]]
        pop.ObjV = np.sin(2 * x1) - np.cos(x2) + 2 * x3 ** 2 - 3 * x4 + (
                    x5 - 3) ** 2 + 7 * x6  # 计算目标函数值，赋值给pop种群对象的ObjV属性

if __name__ == '__main__':
    """================================实例化问题对象==========================="""
    problem = MyProblem() # 生成问题对象
    """==================================种群设置==============================="""
    NIND = 40             # 种群规模
    # 创建区域描述器，这里需要创建两个，前2个变量用RI编码，剩余变量用排列编码
    Encodings = ['RI', 'P']
    Field1 = ea.crtfld(Encodings[0], problem.varTypes[:2], problem.ranges[:,:2], problem.borders[:,:2])
    Field2 = ea.crtfld(Encodings[1], problem.varTypes[2:], problem.ranges[:,2:], problem.borders[:,2:])
    Fields = [Field1, Field2]
    population = ea.PsyPopulation(Encodings, Fields, NIND) # 实例化种群对象（此时种群还没被初始化，仅仅是完成种群对象的实例化）
    """================================算法参数设置============================="""
    myAlgorithm = ea.soea_psy_EGA_templet(problem, population) # 实例化一个算法模板对象
    myAlgorithm.MAXGEN = 25 # 最大进化代数
    """===========================调用算法模板进行种群进化======================="""
    [population, obj_trace, var_trace] = myAlgorithm.run() # 执行算法模板
    population.save() # 把最后一代种群的信息保存到文件中
    # 输出结果
    best_gen = np.argmin(problem.maxormins * obj_trace[:, 1]) # 记录最优种群个体是在哪一代
    best_ObjV = obj_trace[best_gen, 1]
    print('最优的目标函数值为：%s'%(best_ObjV))
    print('最优的控制变量值为：')
    for i in range(var_trace.shape[1]):
        print(var_trace[best_gen, i])
    print('有效进化代数：%s'%(obj_trace.shape[0]))
    print('最优的一代是第 %s 代'%(best_gen + 1))
    print('评价次数：%s'%(myAlgorithm.evalsNum))
    print('时间已过 %s 秒'%(myAlgorithm.passTime))
```

将会出现以下错误：
```
Connected to pydev debugger (build 192.7142.56)
Traceback (most recent call last):
  File "D:\Program Files\PyCharm2019\helpers\pydev\pydevd.py", line 1415, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\PyCharm2019\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/workplace/GA/test3.py", line 50, in <module>
    [population, obj_trace, var_trace] = myAlgorithm.run() # 执行算法模板
  File "D:\Program Files\Python3\lib\site-packages\geatpy\templates\soeas\GA\EGA\soea_psy_EGA_templet.py", line 86, in run
    offspring.Chroms[i] = self.recOpers[i].do(offspring.Chroms[i]) # 重组
  File "D:\Program Files\Python3\lib\site-packages\geatpy\operators\recombination\Xovpmx.py", line 16, in do
    return xovpmx(OldChrom, self.XOVR, self.Half)
  File "core\xovpmx.pyx", line 53, in xovpmx.xovpmx
RuntimeError: error in xovpmx: Chromosome error. (染色体不满足排列编码规则。)
```
这个错误的断点在soea_psy_XXX_templet.py中的：
```
                offspring.Chroms[i] = self.recOpers[i].do(offspring.Chroms[i]) # 重组
```
因为xovpmx好像是封装的，具体是什么问题也看不出来，但是我检查过offspring.Chroms[i]貌似都是符合条件的。。

顺便有两个小问题：

1. 以上方法能通过自己重写一个重组方法解决吗？
2. 在GA运行过程中，变异率和重组率能动态变化吗？
比如说将
```
self.mutOpers[chrom].Pm = 0.1
self.recOpers[chrom].XOVR = 0.5
```
加入到algorithm类run方法的while循环里
有点像模拟退火的意思

**Comment by geatpy-dev** [comment]
@ImLaoBJie 您好！受疫情影响，测试员未能及时就位，此前发布的 2.4.1 发行版中的经过深度重构的排列编码染色体生成函数存在会生成不合法染色体的 BUG，现已将此发行版回退至 2.4.0，您可以重新安装 2.4.0 版本，上述问题即可解决。在这里向您郑重地道歉~！

**Comment by ImLaoBJie** [comment]
@geatpy-dev 谢谢，那结果或者说是performance应该不会有太大区别吧，可能就是速度受点影响？

**Comment by geatpy-dev** [comment]
@ImLaoBJie 之前的2.4.1重点提升了多目标优化NSGA3和RVEA的性能，如果没有用到它们的话回退到2.4.0版本影响不大；进化效果没有影响。

**Comment by ImLaoBJie** [comment]
@geatpy-dev 非常感谢，问题已解决
